name: CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install Homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        
      - name: Install ffmpeg
        run: brew install ffmpeg || true
        
      - name: Download ffmpeg dev
        run: |
          curl https://ffmpeg.zeranoe.com/builds/macos64/dev/ffmpeg-4.2.1-macos64-dev.zip --output ffmpeg-4.2.1-macos64-dev.zip
          unzip ffmpeg-4.2.1-macos64-dev.zip
          cp -pr ffmpeg-4.2.1-macos64-dev/include/lib* include/
      
      - name: Build
        run: ./ci-scripts/build_and_install.sh

  
